export const iconList = [
  {name: 'add_a_photo'},
  {name: 'photo_camera'},
  {name: 'camera_enhance'},
  {name: 'camera'},
  {name: 'content_cut'},
  {name: 'content_paste'},
  {name: 'timer'},
  {name: 'timer_off'},
  {name: 'clock-o'},
  {name: 'arrow_back'},
  {name: 'attach_file'},
  {name: 'check2'},
  {name: 'check'},
  {name: 'close2'},
  {name: 'close'},
  {name: 'plus'},
  {name: 'minus'},
  {name: 'help'},
  {name: 'person'},
  {name: 'playlist_add'},
  // {name: 'instagram'},
  // {name: 'brand'},
  // {name: 'social'},
  {name: 'scan-gun'},
  {name: 'purchasing'},
  {name: 'transfer'},
  {name: 'move'},
  {name: 'picking'},
  {name: 'receiving'},
  {name: 'linecard'},
  {name: 'soe'},
  {name: 'call-queues'},
  {name: 'commodity-pricing1'},
  // {name: 'check-square-solid2 .path1'},
  // {name: 'check-square-solid2 .path2'},
  // {name: 'square-o-solid .path1'},
  // {name: 'square-o-solid .path2'},
  {name: 'catalog'},
  {name: 'yed'},
  {name: 'ratings'},
  {name: 'service-partners'},
  {name: 'supplier'},
  {name: 'suppliers'},
  {name: 'tracking'},
  {name: 'ion-archive'},
  {name: 'inbox'},
  {name: 'ion-close-circled'},
  {name: 'ion-ios-close'},
  {name: 'ion-ios-search-strong'},
  {name: 'ion-ios-search'},
  {name: 'search'},
  {name: 'ellipsis-v'},
  {name: 'reorder-handle'},
  {name: 'arrows'},
  {name: 'add-tax-certificate'},
  {name: 'th-large'},
  {name: 'th'},
  {name: 'th-list'},
  {name: 'home'},
  {name: 'comment'},
  {name: 'folder'},
  {name: 'folder-open'},
  {name: 'flash'},
  {name: 'pied-piper-alt'},
  {name: 'database'},
  {name: 'bell'},
  {name: 'bell-slash'},
  {name: 'bell-o'},
  {name: 'bell-slash-o'},
  {name: 'question-circle-o'},
  {name: 'star'},
  {name: 'star-o'},
  {name: 'user'},
  // {name: 'remove'},
  // {name: 'times'},
  // {name: 'cog'},
  {name: 'gear'},
  {name: 'download'},
  {name: 'refresh'},
  {name: 'lock'},
  {name: 'tag'},
  {name: 'bookmark'},
  {name: 'print'},
  {name: 'text-height'},
  {name: 'image'},
  // {name: 'photo'},
  // {name: 'picture-o'},
  {name: 'pencil'},
  {name: 'map-marker'},
  {name: 'adjust'},
  {name: 'edit'},
  // {name: 'pencil-square-o'},
  {name: 'step-backward'},
  {name: 'backward'},
  {name: 'forward'},
  {name: 'step-forward'},
  {name: 'plus-circle'},
  {name: 'minus-circle'},
  {name: 'times-circle'},
  {name: 'check-circle'},
  {name: 'question-circle'},
  {name: 'info-circle'},
  {name: 'times-circle-o'},
  {name: 'check-circle-o'},
  {name: 'arrow-right'},
  {name: 'exclamation-circle'},
  {name: 'eye'},
  {name: 'eye-slash'},
  {name: 'exclamation-triangle'},
  // {name: 'warning'},
  {name: 'calendar'},
  {name: 'shopping-cart'},
  {name: 'key'},
  // {name: 'cogs'},
  {name: 'gears'},
  {name: 'sign-out'},
  {name: 'upload'},
  {name: 'phone'},
  {name: 'square-o'},
  {name: 'bookmark-o'},
  // {name: 'twitter'},
  // {name: 'facebook'},
  // {name: 'facebook-f'},
  {name: 'filter'},
  // {name: 'group'},
  {name: 'users'},
  {name: 'copy'},
  // {name: 'files-o'},
  {name: 'paperclip'},
  // {name: 'floppy-o'},
  {name: 'save'},
  {name: 'square'},
  {name: 'bars'},
  // {name: 'navicon'},
  // {name: 'reorder'},
  {name: 'list-ul'},
  {name: 'table'},
  {name: 'truck'},
  // {name: 'caret-down'},
  // {name: 'caret-up'},
  {name: 'sort'},
  {name: 'unsorted'},
  {name: 'sort-desc'},
  {name: 'sort-down'},
  {name: 'sort-asc'},
  {name: 'sort-up'},
  {name: 'envelope'},
  {name: 'angle-double-left'},
  {name: 'angle-double-right'},
  {name: 'angle-left'},
  {name: 'angle-right'},
  // {name: 'navigate_before'},
  // {name: 'navigate_next'},
  {name: 'angle-up'},
  {name: 'angle-down'},
  {name: 'ion-chevron-left'},
  {name: 'ion-chevron-right'},
  {name: 'chevron-left'},
  {name: 'chevron-right'},
  {name: 'chevron-up'},
  {name: 'chevron-down'},
  {name: 'mobile'},
  // {name: 'mobile-phone'},
  {name: 'quote-left'},
  {name: 'spinner'},
  {name: 'folder-o'},
  {name: 'exclamation'},
  {name: 'rocket'},
  {name: 'bullseye'},
  {name: 'plus-square'},
  {name: 'plus-square-o'},
  {name: 'minus-square'},
  {name: 'minus-square-o'},
  {name: 'check-square'},
  {name: 'sort-alpha-asc'},
  {name: 'sort-alpha-desc'},
  {name: 'youtube'},
  {name: 'youtube-play'},
  {name: 'circle-o'},
  {name: 'circle'},
  {name: 'dot-circle-o'},
  {name: 'circle-o-notch'},
  {name: 'file-o'},
  {name: 'inquiry'},
  {name: 'file-text-o'},
  {name: 'file-pdf-o'},
  {name: 'file-excel-o'},
  {name: 'paper-plane'},
  // {name: 'send'},
  {name: 'history'},
  {name: 'cc-visa'},
  {name: 'cc-mastercard'},
  {name: 'cc-discover'},
  {name: 'cc-amex'},
  // {name: 'address-card-o'},
  {name: 'vcard-o'},
  // {name: 'drivers-license-o'},
  {name: 'id-card-o'},
  {name: 'trash'},
  {name: 'undelete'},
  {name: 'trash-unavailable'},
  {name: 'paint-brush'},
  {name: 'area-chart'},
  {name: 'heartbeat'},
  {name: 'i-cursor'},
  {name: 'hand-pointer-o'},
  {name: 'import'}
]
